name: Terraform CI/CD
on:
  push:
    branches:
      - master
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: setup terraform
      uses: hashicorp/setup-terraform@v3
      with:
         terraform_version: 1.5.7

    - name: Terraform init
      run: terraform init

    - name: terraform formate check
      run: terraform fmt -check

    - name: terraform validation
      run: terraform validate

    - name: terraform plan
      run: terraform plan

    - name: terraform apply
      run: terraform apply --auto-approve
      
  
