name: Terraform CI/CD
on:
  push:
    branches:
      - master
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: setup terraform
      uses: hashicorp/setup-terraform@v3
      with:
         terraform_version: 1.5.7
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Change to your AWS region
    

    - name: Terraform init
      run: terraform init

    - name: terraform formate check
      run: terraform fmt -check

    - name: terraform validation
      run: terraform validate

    - name: terraform plan
      run: terraform plan

    - name: terraform apply
      run: terraform apply --auto-approve
      

